import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navbar from '../components/Navbar'
import Body from '../components/Body'
import PreLoader from '../components/PreLoader'
import Foooter from '../components/Foooter'






export default function Home() {
  return (
    <div className={styles.container}>
               

      <Head>
        <title>Dream Event</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       

        
          
      </Head>
      {/* <PreLoader/> */}
      <Navbar/>
       <Body/>
       <div className='mt-20'>
      <Foooter />
    
      </div>
   {/* <Practice/>   */}
    </div>
  )
}
